<?php
//Site parameters
define('NIGIRI_PARAM_EMAIL', 'email');
define('NIGIRI_PARAM_TECH_EMAIL', 'technical_email');
define('NIGIRI_PARAM_SITE_NAME', 'site_name');
define('NIGIRI_PARAM_CLEAN_URL', 'clean_urls');
define('NIGIRI_PARAM_URL_PREFIX', 'url_prefix');
define('NIGIRI_PARAM_DEFAULT_PAGE', 'default_page');
define('NIGIRI_PARAM_SUPPORTED_LANGUAGES', 'languages');
define('NIGIRI_PARAM_DEFAULT_LANGUAGE', 'default_language');
define('NIGIRI_PARAM_LOCALES', 'locales');
define('NIGIRI_PARAM_TIMEZONE', 'timezone');
define('NIGIRI_PARAM_EMAIL_SMTP', 'email_smtp');
define('NIGIRI_PARAM_EMAIL_SMTP_CONFIG', 'email_smtp_config');
define('NIGIRI_PARAM_EMAIL_SMTP_HOST', 'email_smtp_config.host');
define('NIGIRI_PARAM_EMAIL_SMTP_PORT', 'email_smtp_config.port');
define('NIGIRI_PARAM_EMAIL_SMTP_USER', 'email_smtp_config.user');
define('NIGIRI_PARAM_EMAIL_SMTP_PASSWORD', 'email_smtp_config.psw');
define('NIGIRI_PARAM_EMAIL_SMTP_SECURE', 'email_smtp_config.secure');
define('NIGIRI_PARAM_DEBUG', 'debug');
define('NIGIRI_PARAM_EXCEPTIONS_VIEWS', 'exceptions_views');
